version: 2.1
jobs:
  build:
    working_directory: ~/test
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependancies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose=1.15.0
      - run:
          name: Start docker compose
          command: |
            docker-compose up -d
      - run:
          name: Start app
          command: |
            ./gradlew run
          